# Generated by Django 6.0.7 on 2026-09-17 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_date_of_birth_customer_member_since_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="bp_diastolic",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="blood pressure (diastolic)"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="bp_recorded_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="blood pressure recorded date"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="bp_systolic",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="blood pressure (systolic)"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="diabetes_status",
            field=models.CharField(
                choices=[("unknown", "Unknown"), ("yes", "Yes"), ("no", "No")],
                default="unknown",
                max_length=10,
                verbose_name="diabetes",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="health_notes",
            field=models.TextField(blank=True, default="", verbose_name="health notes"),
        ),
        # The `user_id` column (UNIQUE FK to `accounts_user`) already exists
        # in the production database from an earlier migration whose file is
        # no longer in the repo (`customers/0002_customer_user`, recorded as
        # applied in `django_migrations`). Register the field in Django state
        # and only create the column when it is actually missing, so this
        # migration works on both the existing database and fresh builds.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="customer",
                    name="user",
                    field=models.OneToOneField(
                        blank=True,
                        help_text="Login account that sees this profile in the Customer Portal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="portal user",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "DO $$ BEGIN "
                        "IF NOT EXISTS (SELECT 1 FROM information_schema.columns "
                        "WHERE table_schema='public' AND table_name='customers_customer' "
                        "AND column_name='user_id') THEN "
                        "ALTER TABLE customers_customer ADD COLUMN user_id bigint NULL; "
                        "ALTER TABLE customers_customer ADD CONSTRAINT "
                        "customers_customer_user_id_a9568d6c_fk_accounts_user_id "
                        "FOREIGN KEY (user_id) REFERENCES accounts_user(id) "
                        "DEFERRABLE INITIALLY DEFERRED; "
                        "ALTER TABLE customers_customer ADD CONSTRAINT "
                        "customers_customer_user_id_key UNIQUE (user_id); "
                        "END IF; END $$;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE customers_customer "
                        "DROP CONSTRAINT IF EXISTS customers_customer_user_id_key; "
                        "ALTER TABLE customers_customer "
                        "DROP CONSTRAINT IF EXISTS "
                        "customers_customer_user_id_a9568d6c_fk_accounts_user_id; "
                        "ALTER TABLE customers_customer DROP COLUMN IF EXISTS user_id;"
                    ),
                ),
            ],
        ),
    ]
