# Generated by Django 6.0.7 on 2026-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_bp_diastolic_customer_bp_recorded_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="diabetes_recorded_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="diabetes recorded date"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="diabetes_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("type1", "Type 1"),
                    ("type2", "Type 2"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
                verbose_name="diabetes type",
            ),
        ),
    ]
