# Generated by Django 6.0.7 on 2026-09-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_diabetes_recorded_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodPressureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic", models.PositiveIntegerField(verbose_name="systolic")),
                ("diastolic", models.PositiveIntegerField(verbose_name="diastolic")),
                ("recorded_date", models.DateField(verbose_name="recorded date")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_pressure_records",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "blood pressure record",
                "verbose_name_plural": "blood pressure records",
                "ordering": ["-recorded_date"],
            },
        ),
        migrations.CreateModel(
            name="DiabetesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diabetes_status",
                    models.CharField(
                        choices=[("unknown", "Unknown"), ("yes", "Yes"), ("no", "No")],
                        default="unknown",
                        max_length=10,
                        verbose_name="diabetes status",
                    ),
                ),
                (
                    "diabetes_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("type1", "Type 1"),
                            ("type2", "Type 2"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="diabetes type",
                    ),
                ),
                ("recorded_date", models.DateField(verbose_name="recorded date")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diabetes_records",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "diabetes record",
                "verbose_name_plural": "diabetes records",
                "ordering": ["-recorded_date"],
            },
        ),
    ]
