# Generated by Django 6.0.7 on 2026-09-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryproduct",
            name="barcode",
        ),
    ]
