# Generated by Django 6.0.7 on 2026-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_inventoryproduct_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryproduct",
            name="generic_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
