# Generated by Django 6.0.7 on 2026-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventoryproduct_generic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryproduct",
            name="company_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inventoryproduct",
            name="dosage_form",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
