# Generated by Django 6.0.6 on 2026-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_supplier_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="box_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Selling price for one full box.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="strip_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Selling price for one full strip.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="units_per_box",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of PCs contained in one box.", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="units_per_strip",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of PCs contained in one strip.", null=True
            ),
        ),
    ]
