# Generated by Django 6.0.6 on 2026-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_product_box_price_product_strip_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="units_per_box",
        ),
        migrations.RemoveField(
            model_name="product",
            name="units_per_strip",
        ),
        migrations.AddField(
            model_name="product",
            name="pcs_per_box",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of PCs in one full box. Derived as pcs_per_strip x strips_per_box when both are set.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pcs_per_strip",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of PCs contained in one strip.", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="strips_per_box",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of strips contained in one box.",
                null=True,
            ),
        ),
    ]
