# Generated by Django 6.0.7 on 2026-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_product_units_per_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="company",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pharmacy or pharmaceutical company the contact works for.",
                max_length=255,
                verbose_name="pharmacy/company they work for",
            ),
        ),
    ]
