# Generated by Django 6.0.7 on 2026-09-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_seed_demo_suppliers"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierRestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(
                        help_text="Stock level (in PCs) when this entry was created or last updated."
                    ),
                ),
                (
                    "stock_unit",
                    models.CharField(
                        help_text="The unit at which the threshold was evaluated (pc, strip, box).",
                        max_length=10,
                    ),
                ),
                (
                    "threshold",
                    models.IntegerField(
                        help_text="The absolute PC threshold that triggered this entry."
                    ),
                ),
                (
                    "suggested_quantity",
                    models.IntegerField(
                        default=0, help_text="Suggested restock quantity in PCs."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ordered", "Ordered"),
                            ("received", "Received"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_entries",
                        to="inventory.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_items",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier restock",
                "verbose_name_plural": "supplier restocks",
                "ordering": ["-created_at"],
                "unique_together": {("supplier", "product")},
            },
        ),
    ]
