# Generated by Django 6.0.6 on 2026-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_salepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="unit",
            field=models.CharField(
                choices=[("pc", "PC"), ("strip", "Strip"), ("box", "Box")],
                default="pc",
                max_length=10,
            ),
        ),
    ]
