# Generated by Django 6.0.6 on 2026-08-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_saleitem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="quantity_pcs",
            field=models.PositiveIntegerField(
                default=0,
                help_text="PC-equivalent quantity captured at sale time so stock can be restored even if the product's pack sizes change later.",
            ),
        ),
    ]
